name = "Jinja2 (YAML)"
grammar = "jinja"
path_suffixes = ["yaml.jinja", "yaml.jinja2", "yaml.j2", "yml.jinja", "yml.jinja2", "yml.j2"]
block_comment = ["{# ", " #}"]
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
]
