name = "Jinja2 (Markdown)"
grammar = "jinja"
path_suffixes = ["md.jinja", "md.jinja2", "md.j2"]
autoclose_before = "<>})],;:"
block_comment = { start = "{# ", prefix = "", end = " #}", tab_size = 0 }
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "[", end = "]", close = true, newline = false, not_in = ["comment", "string"] },
]
