name = "Jinja2 (Dockerfile)"
grammar = "jinja"
path_suffixes = ["Dockerfile.jinja", "Dockerfile.jinja2", "Dockerfile.j2", "dockerfile.jinja", "dockerfile.jinja2", "dockerfile.j2"]
block_comment = ["{# ", " #}"]
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
]
