name = "Jinja2 (TypeScript)"
grammar = "jinja"
path_suffixes = ["ts.jinja", "ts.jinja2", "ts.j2"]
autoclose_before = "<>})],;:"
block_comment = { start = "{# ", prefix = "", end = " #}", tab_size = 0 }
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "[", end = "]", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "{", end = "}", close = true, newline = true },
  { start = "<", end = ">", close = false, newline = false },
]
